#pragma once

// Names of every function in the project, so any file can call any other.
// The actual code for each lives in its own system file (farm.cpp, battle.cpp, etc.).


void Debug();
int getTotalCards();
int getTotalHeadGear();
int getTotalBodyGear();
int getTotalGems();
int getTotalCounters();
void ApplyBacklight();
void ApplyLed();
bool HasUnownedCards();
bool HasUnownedHeadGear();
bool HasUnownedBodyGear();
bool HasUnownedGems();
bool CanShowRareItem(int shopItemListIndex);
int GrantCard(int cardIndex = -1);
int GrantHeadGear(int gearIndex = -1);
int GrantBodyGear(int gearIndex = -1);
int GrantGem(int gemIndex = -1);
int GrantDDCard(int cardIndex = -1);
void InitializeDeepDungeon();
void ResetDeepDungeon();
void DrawDDGemSelect();
void UpdateDDGemSelect();
void DrawDDGemConfirm();
void DrawDDGemTooltip();
void DrawDDMeritSelect();
void DrawDDMeritBar(int i);
void UpdateDDMeritSelect();
void RollDraftChoices();
void RollMeritDraft();
void RemoveMerit(int id);
void DrawMeritDiscard();
void DrawMeritDiscardRows();
void DrawMeritDiscardConfirm();
void DrawDiscardYesNo();
void DrawDDCardDraft();
void UpdateDDCardDraft();
void DrawDDCardDraftTooltip();
void DrawMeritScreen();
void DrawRunGemIcon();
void DrawMeritPage();
void DrawMeritRows();
void DrawAfflictionScreen();
void DrawAfflictionRows();
void DrawAfflictionPage();
void DrawMeritTooltipById(int m);
void DrawGemTooltipById(int g);
void DrawAfflictionTooltipById(int a, int lvl);
void DrawDDMeritTooltip();
void SaveDeepDungeon();
void CreateDDDeck(int deckNumber);
int getDeckBaseAddr();
int getEquippedDeckAddr();
bool ownsCard(int cardIndex);
int getEquippedDeck();
void saveEquippedDeck(int deck);
void DisplayBatteryPercentage();
void SavePetStats();
void LoadPetStats();
void AutoSave();
void CalculateMaxHP();
void CalculateHunger();
void CalculateStamina();
void CalculateMood();
void EmotionState();
float GetGemAtkMult();
float GetGemDefMult();
float GetGemSpdMult();
float GetGemHPMult();
int GetMeritCap();
int GetAfflictionCap();
int GetAfflictionLevel(int id);
bool HasMerit(int id);
int getTotalBosses();
int GetDDCardCount();
void GrantBossAffliction();
void DrawBossAfflictionPopup();
void QueueEffectMsg(String msg, int target);
void DrawCardTooltip(Card c);
void DrawCounterTooltip();
void DrawEffectPointer(int target);
void ButtonManager();
void CenterText(String text, int yCord);
void DisplayTime();
void DisplayVentureTime();
void DisplayInjuryTime();
void ClampStats();
void ManageInventory();
void ManageGemInventory();
bool IsInventoryFull(int itemAddress);
void UseItem();
void sortCardsByName(SortedCard arr[], int size);
void CompileListMenu(String menu);
int OwnershipCount(byte ownership[32]);
void ManageGems(String _pet, bool remove);
char NextChar(char current);
void playMelody();
void SaveFarmData();
void UpdateFarm();
void PlantSeed(int seedType);
void HarvestPlant();
bool HasHarvestableCrop();
void SaveCredits();
void AddCredits(int amount);
bool SpendCredits(int amount);
void ScreenOff();
void DrawScene();
void DrawMainMenu();
void ToggleMenus();
void BattleManager();
void DrawBackground();
void DrawCharacter(int xPos, int yPos, bool mirror);
void DrawEnemy(int xPos);
void CombineImages(const uint16_t* bottomImage, const uint16_t* middleImage, const uint16_t* topImage, uint16_t* combinedImage, bool bodyBehindHead);
void CreateCharacter(String _pet, const uint16_t* headSprites[], const uint16_t* bodySprites[]);
void CreateWardrobeCharacter(int wardrobe, const uint16_t* headSprites[], const uint16_t* bodySprites[]);
void MirrorHorizontally(const uint16_t* combinedImage, uint16_t* mirroredImage);
uint16_t* GetMirrorPet(int frame);
void ShowTitleScreen();
void WalkPet();
void VentureWalk();
void VentureEncounter();
void TutorialManager();
void DrawFarm();
void DrawPot(int potIndex);
void DrawFarmArrow();
void DrawHarvestMessage();
void ShowSeedSelection();
void pinoutInit();
void displayInit();
void ReadSaveData();
void SaveDataInit();
void FormatData();
int base64_decode(uint8_t* output, const char* input, int inputLen);
uint32_t crc32(uint8_t* data, size_t len);
void CopyEEPROMToFlash();
void CheckAndLoadRestore();
void LEDManager();
void LEDBlink(int blinkDelay, int waitDelay, int onTime);
void LEDRainbow(uint8_t wait);
void LEDBreath(uint32_t color, uint16_t duration, uint8_t brightness);
void LEDPulseOnce(uint32_t color, uint16_t duration, uint8_t brightness);
void BatteryInfo();
void drawingBatteryIcon(int imgNum);
void CreateDeck(int deckNumber);
void Shuffle(Card deck[]);
void swap(Card& a, Card& b);
void InitializeBattle();
void UpdateHealthBars();
void UpdateBattleCards(int selectedCard, bool refresh);
void UpdateCounters(int selected);
void BattleCardSelection();
void CalculateSpeed();
int ChooseEnemyCard();
bool HasCounter(String target, String counterType);
void TryHeal(String target, int amount, String successMessage = "HP RESTORED!");
void AddStacks(String target, String counterType, int stacks = 1);
void SetStacks(String target, String counterType, int level);
void RemoveStacks(String target, String counterType, int stacks = 1);
void UseCard(String user);
void ManageCounters(String target, String counter, bool _canReplace);
void CounterEffects(String effect, bool refresh);
void CalculateDamage(String target, Card _card);
int GetStackLevel(String target, String counterType);
void HandleCardEffects(String target, Card _card, float &attackModifier, float &defenseModifier);
void VentureMenu(int dir);
void InitializeEnemy(int _index, bool isRandom);
void GenerateRandomEnemy();
int GrantStageReward();
void SaveEventFlags();
void LoadEventFlags();
void TriggerRandomEvent();
void UpdateEventWalk();
void DrawEventPrompt();
void DrawEventResult();
void ExecuteEvent();
void HandleEventButton();
void CheckRandomEvent();
void pushScaled(int x, int y, int w, int h, const uint16_t* data, uint16_t transparent);
void pushScaled(int x, int y, int w, int h, const uint16_t* data);
void pushScaled(TFT_eSprite &dst, int x, int y, int w, int h, const uint16_t* data, uint16_t transparent);
