#pragma once

// Thought and dream text for the thought bubble.
// Each entry is one screen: up to 4 lines of 13 characters, split with |
// Allowed characters: A to Z, 0 to 9, space and ! ? . , ' & " (write a quote as \")
// {P} = your Pico's name (max 10), {E} = the last enemy fought (max 10).
// Lines with {E} only show for a few hours after a venture battle.
// Placeholders sit alone on their line, or as {P}'S / {E}'S.
// Add or remove entries freely; counts are calculated automatically.
// Keep the nature pools in the same order as the natures (CHEERFUL through GRUMPY).

#pragma region THOUGHTS

// Anytime, no condition
const char* const TH_GENERAL[] = {
  "{P}|WONDERS IF|CLOUDS TASTE|LIKE CAKE",
  "{P}|IS SURE IT'S|THE MAIN|CHARACTER",
  "{P}|WANTS TO|START A BAND",
  "{P}|WONDERS IF|PEBBLES HAVE|FEELINGS",
  "{P}|THINKS IT|HEARD A BUG|SNEEZE",
  "{P}|IS STARING|AT THE SKY|SUSPICIOUSLY",
  "{P}|COULD BEAT|EVIL DAVE.|PROBABLY.",
  "{P}|DECIDED ITS|LEFT EYE IS|THE BEST ONE",
  "{P}|IS SPINNING|TO SEE IF IT|CAN FLY",
  "{P}|FORGOT WHAT|IT WAS|THINKING",
  "{P}|IS HUMMING|A SONG IT|MADE UP",
  "{P}|THINKS THE|FLOOR IS NICE|TODAY",
  "{P}|IS COUNTING|TO A MILLION.|IT'S AT TWO",
  "{P}|WONDERS|WHAT WHALES|DREAM ABOUT",
  "{P}|WANTS A HAT|MADE OF HATS",
  "{P}|THINKS IT|DESERVES A|BIOGRAPHY",
  "{P}|ISN'T|STARING. IT'S|THINKING",
  "{P}|IS WAITING|FOR SNACK|TIME",
  "{P}|LOOKS HAPPY|YOU CHECKED|IN",
  "{P}|WONDERS|WHAT'S PAST|THE SCREEN",
  "{P}|WAVED AT A|BIRD. IT DID|NOT WAVE BACK",
  "{P}|IS ENJOYING|EXISTING|TODAY",
  "{P}|THINKS IT'D|MAKE A GREAT|ROLE MODEL",
  "{P}|IS JUST...|SITTING",
  "{P}'S|BRAIN IS|MOSTLY NOISE|TODAY",
  "{P}|KNOWS IT'S|ADORABLE",
  "{P}|IS THINKING|ABOUT|THINKING",
  "{P}|SAW A CLOUD|SHAPED LIKE|A CLOUD",
  "{P}|IS TRYING|TO LEARN TO|WHISTLE",
  "{P}|IS PLOTTING|SOMETHING.|IT WON'T SAY",
  "{P}|IS REALLY|GOOD AT|STANDING",
  "{P}|IS STARING AT|THE FLOOR",
  "{P}|WISHES|CREDITS GREW|ON TREES",
  "{P}|HAD A GREAT|IDEA. IT'S|GONE NOW",
  "{P}|IS LOST IN|THOUGHT",
  "{P}|THINKS IT'S|THE BEST PICO|EVER",
  "{P}|WONDERS IF|{E}|IS OKAY",
  "{P}|REMEMBERS|{E}|FONDLY",
  "{P}|SAYS|{E}|OWES IT ONE",
  "{P}|THINKS THE|MOON IS A|NIGHT LIGHT",
  "{P}|COULD GO|FOR A NAP",
  "{P}'S|TUMMY MADE|A NOISE",
  "{P}|IS PRETENDING|TO BE A|ROBOT",
  "{P}|IS JUST|VIBING",
  "{P}|IS LOOKING|FOR A GOOD|HIDING SPOT",
  "{P}|IS BUSY|BEING|AWESOME",
  "{P}|IS HAVING|DEEP|THOUGHTS",
  "{P}|IS DOING|IT. WHATEVER|\"IT\" IS",
  "{P}|PRACTICED|ITS SERIOUS|FACE",
  "{P}|IS ON A VERY|IMPORTANT|WALK",
  "{P}|THINKS THE|PIXELS LOOK|CRISPY TODAY",
  "{P}|WAVES HELLO|TO YOU!",
  "{P}|ISN'T LOST.|IT'S|EXPLORING",
  "{P}|IS COUNTING|ITS PIXELS",
  "{P}|WONDERS|HOW A TAIL|WOULD LOOK",
  "{P}|FEELS LIKE A|FRIENDLY|FIREBALL",
  "{P}|IS DOING|NOTHING. LIKE|A PRO",
  "{P}|IS LOOKING|AT YOU,|SCHEMING",
  "{P}|YAWNED AND|PRETENDED IT|DIDN'T",
  "{P}|IS WATCHING|A SPECK OF|DUST FLOAT",
  "{P}|TRIED TO|WINK. BOTH|EYES CLOSED",
  "{P}|IS HAVING A|STARING|CONTEST",
  "{P}|IS LOSING|A STARING|CONTEST",
  "{P}|THINKS IT|HEARD ITS|NAME",
  "{P}|WONDERS IF|ITS SHADOW|GETS TIRED",
  "{P}|IS TAPPING|ITS FOOT TO|A BEAT",
  "{P}|IS HOLDING|ITS BREATH|SPONTANEOUSLY",
  "{P}|SNEEZED.|IT LOOKS|SURPRISED",
  "{P}|HICCUPED",
  "{P}|IS PRETENDING|TO BE A|STATUE",
  "{P}|WONDERS IF|THE WALLS|CAN HEAR IT",
  "{P}|IS TRYING|TO SCRATCH|ITS FACE",
  "{P}|FORGOT|WHICH WAY|IT WAS GOING",
  "{P}|IS HAVING|A MOMENT",
  "{P}|IS|DAYDREAMING|AGAIN",
  "{P}|WONDERS|WHAT TIME|IT IS",
  "{P}|IS RANKING|ITS FAVORITE|CARDS",
  "{P}|THINKS|FIREBALL IS|OVERRATED",
  "{P}|IS PRACTICING|ITS VICTORY|POSE",
  "{P}|IS COUNTING|THE PIXELS.|IT GAVE UP",
  "{P}|WONDERS IF|IT'S TALLER|TODAY",
  "{P}|THINKS A|HAT WOULD|LOOK GOOD",
  "{P}|IS WONDERING|ABOUT|EVIL DAVE",
  "{P}|THINKS|EVIL DAVE|NEEDS A HUG",
  "{P}|IS SWATTING|AN IMAGINARY|BUG",
  "{P}|THINKS|TODAY IS A|GOOD DAY",
  "{P}|WONDERS IF|GEMS ARE|JUST ROCKS",
  "{P}|IS POLITELY|IGNORING YOU",
  "{P}|WANTS|ATTENTION.|MAYBE",
  "{P}|IS WALKING|IN A VERY|STRAIGHT LINE",
  "{P}|IS SURE IT|LEFT THE|STOVE ON",
  "{P}|LOST ITS|PET ROCK",
  "{P}|IS HUMMING|OFF KEY",
  "{P}|IS DOING|ITS BEST",
  "{P}|THINKS IT|LOOKS EXTRA|CUTE TODAY",
  "{P}|IS PONDERING|THE MEANING|OF CREDITS",
  "{P}|IS WATCHING|THE BATTERY|ICON",
  "{P}|WONDERS IF|THE SHOP HAS|NEW STUFF",
  "{P}|THINKS|EVERY CARD|HAS A STORY",
  "{P}|IS SNIFFING|THE AIR",
  "{P}|STRETCHED.|IT FEELS|GREAT",
  "{P}|IS MAKING|A WISH",
  "{P}|WONDERS IF|{E}|LIKES CAKE",
  "{P}|IS SURE|{E}|CHEATED",
  "{P}|THINKS|{E}|HAD COOL GEAR",
  "{P}|IS TELLING|ITSELF A|JOKE",
  "{P}|LAUGHED AT|ITS OWN JOKE",
  "{P}|IS GUARDING|THE SCREEN",
  "{P}|IS WONDERING|WHERE THE|DAY WENT",
  "{P}|IS FEELING|PHILOSOPHICAL",
  "{P}|IS JUST|HAPPY TO|BE HERE",
  "{P}|IS LOOKING|FOR SOMETHING|IT LOST",
  "{P}|FOUND|NOTHING.|AS EXPECTED",
  "{P}|IS WIGGLING|FOR NO|REASON",
  "{P}|IS LISTENING|TO THE|SILENCE",
  "{P}|THINKS IT|COULD BEAT A|BOSS TODAY",
  "{P}|WONDERS IF|ITS DECK IS|ANY GOOD",
  "{P}|IS HAVING|A VERY|NORMAL DAY",
  "{P}|IS STARING|AT YOU",
  "{P}'S|HEAD IS|EMPTY"
};

// Hunger 30 or less
const char* const TH_HUNGRY[] = {
  "{P}'S|TUMMY IS|RUMBLING",
  "{P}|IS THINKING|ABOUT FOOD.|ONLY FOOD",
  "{P}|WANTS A|SWEET FRUIT",
  "{P}|COULD EAT A|WHOLE FARM",
  "{P}|TRIED TO|EAT A ROCK",
  "{P}|LOOKS|HUNGRY",
  "{P}|WOULD TRADE|A GEM FOR|A SNACK",
  "{P}|IS GIVING|YOU HUNGRY|EYES",
  "{P}|IS EYEING|THE FARM",
  "{P}|IS DREAMING|OF TASTY|CAKE",
  "{P}|IS TOO|HUNGRY TO|THINK",
  "{P}|IS CHEWING|ON NOTHING",
  "{P}|WANTS|A SNACK.|NOW",
  "{P}|THINKS ITS|BELLY IS|SINGING",
  "{P}|IS STARING|AT THE|INVENTORY",
  "{P}|WOULD EAT|ANYTHING|RIGHT NOW",
};

// Stamina 30 or less
const char* const TH_TIRED[] = {
  "{P}|IS FIGHTING|TO STAY|AWAKE",
  "{P}'S|LEGS FEEL|LIKE NOODLES",
  "{P}|IS TRYING|TO NAP|STANDING UP",
  "{P}|IS RUNNING|LOW ON|ENERGY",
  "{P}|WANTS AN|ENERGY DRINK",
  "{P}|LET OUT A|BIG YAWN",
  "{P}|NEEDS A|BREAK",
  "{P}|IS RUNNING|ON FUMES",
  "{P}|IS DOZING|OFF",
  "{P}|IS HAVING|TROUBLE|STANDING",
  "{P}|KEEPS|BLINKING|SLOWLY",
  "{P}|WANTS TO|LIE DOWN",
  "{P}|IS DRAGGING|ITS FEET",
  "{P}|IS NODDING|OFF",
  "{P}|COULD|SLEEP FOR|A WEEK",
  "{P}|IS ALL|TUCKERED OUT",
};

// Mood 30 to 49
const char* const TH_SAD[] = {
  "{P}|SEEMS A|LITTLE DOWN",
  "{P}|COULD USE|A PAT ON|THE HEAD",
  "{P}|FEELS A BIT|OFF",
  "{P}|SIGHED",
  "{P}|IS HAVING|A GRAY DAY",
  "{P}|IS THINKING|ABOUT TASTY|CAKE",
  "{P}|IS LOOKING|AT THE|GROUND",
  "{P}|COULD USE|SOME COMPANY",
  "{P}|IS QUIETER|THAN USUAL",
  "{P}|IS MOPING",
  "{P}|WANTS A|LITTLE LOVE",
  "{P}|IS FEELING|BLUE",
};

// Mood under 30
const char* const TH_ANGRY[] = {
  "{P}|IS NOT|HAPPY",
  "{P}|HUFFED",
  "{P}|IS GIVING|YOU THE COLD|SHOULDER",
  "{P}|IS MAD AND|DOESN'T KNOW|WHY",
  "{P}|IS|GRUMBLING",
  "{P}|THINKS|EVERYTHING|IS THE WORST",
  "{P}|IS|STOMPING",
  "{P}|IS POUTING",
  "{P}|WANTS AN|APOLOGY",
  "{P}|IS SULKING|IN THE|CORNER",
  "{P}|IS FUMING",
  "{P}|CROSSED|ITS ARMS",
};

// Mood 90 or more
const char* const TH_HAPPY[] = {
  "{P}|IS HAVING|THE BEST DAY|EVER",
  "{P}|FEELS|AMAZING",
  "{P}|IS|GIGGLING",
  "{P}|THINKS LIFE|IS PRETTY|GOOD",
  "{P}|THINKS YOU|ARE THE BEST",
  "{P}|IS DOING A|LITTLE DANCE",
  "{P}|IS|BEAMING",
  "{P}|IS FULL|OF JOY",
  "{P}|IS|WHISTLING",
  "{P}|IS BOUNCING|AROUND",
  "{P}|IS ON|CLOUD NINE",
  "{P}|THINKS|EVERYTHING|IS PERFECT",
  "{P}|IS HUMMING|A HAPPY TUNE",
  "{P}|CAN'T STOP|SMILING",
  "{P}|IS IN A|GREAT MOOD",
  "{P}|IS GLOWING",
};

// HP under half
const char* const TH_LOW_HP[] = {
  "{P}|IS STILL|SORE",
  "{P}|IS HURTING|A LITTLE",
  "{P}|WANTS A|HEALTH POTION",
  "{P}|INSISTS|IT'S FINE.|IT'S NOT",
  "{P}|NEEDS TO|PATCH UP",
  "{P}|IS WOBBLY|BUT BRAVE",
  "{P}|IS TAKING|IT EASY",
  "{P}|IS NURSING|A BRUISE",
  "{P}|IS MOVING|CAREFULLY",
  "{P}|WINCED",
  "{P}|COULD USE|SOME REST",
  "{P}|IS A BIT|BANGED UP",
};

// Pico is injured
const char* const TH_INJURED[] = {
  "{P}|HURTS|EVERYWHERE",
  "{P}|NEEDS A|MED KIT",
  "{P}|IS LYING|STILL FOR|A WHILE",
  "{P}|IS REPLAYING|THAT FIGHT.|IT HURTS",
  "{P}|WHIMPERED",
  "{P}|IS HEALING.|SLOWLY",
  "{P}|IS TOO SORE|TO MOVE",
  "{P}|IS WAITING|TO FEEL|BETTER",
  "{P}|THINKS IT|NEEDS A|DOCTOR",
  "{P}|IS RESTING|ITS WOUNDS",
  "{P}|IS BEING|VERY BRAVE|ABOUT IT",
  "{P}|IS COUNTING|DOWN THE|MINUTES",
};

// Venture cooldown running
const char* const TH_COOLDOWN[] = {
  "{P}|IS RESTING|BEFORE THE|NEXT VENTURE",
  "{P}|WONDERS|WHAT'S ON THE|NEXT FLOOR",
  "{P}|WONDERS|WHO IT'LL|FIGHT NEXT",
  "{P}|IS ALMOST|READY TO|GO AGAIN",
  "{P}|IS CATCHING|ITS BREATH",
  "{P}|IS THINKING|ABOUT ITS|DECK",
  "{P}|WANTS TO|SWAP A CARD|OR TWO",
  "{P}|HAS A GOOD|FEELING ABOUT|THE NEXT ONE",
  "{P}|IS|STRETCHING|FOR LATER",
  "{P}|IS PLANNING|ITS NEXT|MOVE",
  "{P}|IS WAITING|PATIENTLY.|SORT OF",
  "{P}|IS GETTING|RESTLESS",
  "{P}|IS GOING|OVER LAST|BATTLE",
  "{P}|IS SIZING|UP ITS|CARDS",
  "{P}|WANTS TO|GO NOW",
  "{P}|IS TAKING|FIVE",
};

// Deep Dungeon run active
const char* const TH_DEEP_DUNGEON[] = {
  "{P}|THINKS IT'S|REALLY DARK|DOWN HERE",
  "{P}|WONDERS HOW|DEEP THIS|GOES",
  "{P}|KNOWS|THERE'S NO|TURNING BACK",
  "{P}|THINKS EACH|FLOOR GETS|SCARIER",
  "{P}|HEARD|SOMETHING|BELOW",
  "{P}|IS STAYING|FOCUSED",
  "{P}|IS BRACING|FOR THE NEXT|BOSS",
  "{P}|FEELS THE|DUNGEON|WATCHING",
  "{P}|IS COUNTING|THE FLOORS",
  "{P}|THINKS THE|WALLS MOVED",
  "{P}|IS HOLDING|ITS GEM|TIGHT",
  "{P}|WONDERS WHO|MADE THIS|PLACE",
  "{P}|IS TRYING|NOT TO GET|LOST",
  "{P}|IS FEELING|THE PRESSURE",
  "{P}|THINKS ONE|MORE FLOOR|IS FINE",
  "{P}|HEARD AN|ECHO",
};

// A farm pot is ready
const char* const TH_CROPS_READY[] = {
  "{P}|NOTICED THE|FARM IS|READY",
  "{P}|SMELLS|FRESH FRUIT",
  "{P}|THINKS|SOMETHING|IS RIPE",
  "{P}|THINKS IT'S|HARVEST TIME",
  "{P}|KEEPS|GLANCING AT|THE FARM",
  "{P}|DOESN'T|WANT THE|CROPS TO WAIT",
  "{P}|CAN'T WAIT|TO HARVEST",
  "{P}|IS DROOLING|OVER THE|FARM",
  "{P}|THINKS THE|PLANTS LOOK|READY",
  "{P}|WANTS TO|PICK|SOMETHING",
  "{P}|IS PROUD|OF THE CROPS",
  "{P}|IS POINTING|AT THE FARM",
};

// 2000+ credits
const char* const TH_RICH[] = {
  "{P}|FEELS|LOADED",
  "{P}|LOVES HOW|SHINY ITS|CREDITS ARE",
  "{P}|IS DREAMING|OF A SHOPPING|SPREE",
  "{P}|COULD BUY|ALMOST|ANYTHING",
  "{P}|IS LIVING|THE HIGH LIFE",
  "{P}|IS COUNTING|CREDITS",
  "{P}|IS FEELING|FANCY",
  "{P}|THINKS IT|DESERVES A|TREAT",
  "{P}|IS ADMIRING|ITS WEALTH",
  "{P}|WANTS TO|VISIT THE|SHOP",
  "{P}|IS ACTING|VERY RICH",
  "{P}|IS PLANNING|A BIG|PURCHASE",
};

// Under 50 credits
const char* const TH_BROKE[] = {
  "{P}|CHECKED ITS|POCKETS.|EMPTY",
  "{P}|FOUND LINT.|NOT A CREDIT",
  "{P}|THINKS WE|NEED MORE|CREDITS",
  "{P}|IS FLAT|BROKE",
  "{P}|WONDERS IF|THE SHOP|TAKES HUGS",
  "{P}'S|POCKETS ARE|EMPTY. ITS|HEART IS FULL",
  "{P}|IS LOOKING|FOR CREDITS|ON THE FLOOR",
  "{P}|THINKS IT'S|TIME TO|VENTURE",
  "{P}|IS ON A|TIGHT BUDGET",
  "{P}|WINDOW|SHOPPED.|SADLY",
  "{P}|IS COUNTING|ZERO CREDITS|AGAIN",
  "{P}|THINKS WE|SHOULD SAVE",
};

// Won a battle today
const char* const TH_WON[] = {
  "{P}|IS STILL|PROUD OF|THAT WIN",
  "{P}|THINKS|VICTORY|TASTES SWEET",
  "{P}|IS ON|A ROLL",
  "{P}|THINKS THEY|NEVER STOOD|A CHANCE",
  "{P}|IS DOING A|VICTORY|DANCE",
  "{P}|IS STILL|BUZZING FROM|THAT FIGHT",
  "{P}|IS REPLAYING|THE WIN|IN ITS HEAD",
  "{P}|IS FEELING|UNSTOPPABLE",
  "{P}|IS TELLING|EVERYONE|IT WON",
  "{P}|IS HUMMING|A VICTORY|SONG",
  "{P}|THINKS IT|EARNED A|SNACK",
  "{P}|IS PUFFING|ITS CHEST",
};

// Lost a battle today
const char* const TH_LOST[] = {
  "{P}|WILL GET|THEM NEXT|TIME",
  "{P}|IS STILL|MAD ABOUT|THAT LOSS",
  "{P}|SAYS THAT|ONE DIDN'T|COUNT",
  "{P}|THINKS IT|NEEDS A|BETTER DECK",
  "{P}|IS CALLING|IT PRACTICE",
  "{P}|IS STILL|STINGING FROM|THAT ONE",
  "{P}|IS GOING|OVER WHAT|WENT WRONG",
  "{P}|WANTS A|REMATCH",
  "{P}|IS LICKING|ITS WOUNDS",
  "{P}|IS BLAMING|THE CARDS",
  "{P}|IS TRAINING|IN ITS HEAD",
  "{P}|WILL NOT|TALK ABOUT IT",
};

// Beat a boss today
const char* const TH_BOSS[] = {
  "{P}|CAN'T|BELIEVE IT|BEAT A BOSS",
  "{P}|IS LOOKING|FOR THE NEXT|BOSS",
  "{P}|THINKS|IT'S A BIG|DEAL NOW",
  "{P}|THINKS THE|BOSS WAS BIG.|IT'S BIGGER",
  "{P}|EXPECTS|SONGS TO BE|WRITTEN",
  "{P}|IS STILL|SHAKING FROM|THE BOSS",
  "{P}|IS TELLING|EVERYONE|ABOUT IT",
  "{P}|THINKS|NOTHING CAN|STOP IT",
  "{P}|IS POSING|LIKE A HERO",
  "{P}|THINKS IT|EARNED A NAP",
};

// Hit a slots jackpot today
const char* const TH_JACKPOT[] = {
  "{P}|IS STILL|SHAKING FROM|THAT JACKPOT",
  "{P}|THINKS THE|SLOTS LOVE IT",
  "{P}|FEELS LIKE|THE LUCKIEST|PICO ALIVE",
  "{P}|WANTS TO|PLAY AGAIN",
  "{P}|IS HUMMING|DING DING|DING",
  "{P}|THINKS IT|HAS A SYSTEM",
  "{P}|IS FEELING|LUCKY",
  "{P}|CAN STILL|HEAR THE|SLOTS",
  "{P}|THINKS|TODAY IS ITS|LUCKY DAY",
  "{P}|IS BRAGGING|ABOUT ITS|LUCK",
};

// Got new gear today
const char* const TH_GEAR[] = {
  "{P}|WANTS TO|SHOW OFF ITS|NEW GEAR",
  "{P}|FEELS|FANCY",
  "{P}|THINKS IT'S|A FASHION|ICON",
  "{P}|WANTS TO|TRY ON ITS|NEW GEAR",
  "{P}|THINKS THE|WARDROBE IS|FILLING UP",
  "{P}|IS STRIKING|A POSE",
  "{P}|THINKS IT|LOOKS GREAT",
  "{P}|WANTS A|NEW OUTFIT",
  "{P}|IS ADMIRING|ITS NEW|LOOK",
  "{P}|THINKS|EVERYONE IS|JEALOUS",
};

// Harvested today
const char* const TH_HARVEST[] = {
  "{P}|LOVES FRESH|FARM FOOD",
  "{P}|THINKS IT'S|A FARMER NOW",
  "{P}|SAYS HOME|GROWN IS BEST",
  "{P}|IS PROUD|OF ITS|LITTLE POTS",
  "{P}|THINKS THE|FARM PROVIDES",
  "{P}|IS ALREADY|PLANNING THE|NEXT CROP",
  "{P}|HAS DIRT|ON ITS FEET",
  "{P}|THINKS IT|HAS A GREEN|THUMB",
  "{P}|IS ADMIRING|THE HARVEST",
  "{P}|SMELLS|LIKE FRUIT",
};

// Good random event today
const char* const TH_GOOD_EVENT[] = {
  "{P}|THINKS|TODAY IS FULL|OF SURPRISES",
  "{P}|FEELS|LUCKY TODAY",
  "{P}|THINKS GOOD|THINGS KEEP|HAPPENING",
  "{P}|THINKS THE|WORLD IS|BEING NICE",
  "{P}|LOVES|SURPRISES",
  "{P}|IS STILL|SMILING|ABOUT EARLIER",
  "{P}|THINKS|THE STARS|ALIGNED",
  "{P}|WANTS MORE|DAYS LIKE|THIS",
  "{P}|THINKS IT'S|ON A LUCKY|STREAK",
  "{P}|IS FEELING|BLESSED",
};

// Bad random event today
const char* const TH_BAD_EVENT[] = {
  "{P}|THINKS|TODAY HAS|BEEN WEIRD",
  "{P}|WONDERS WHY|THIS ALWAYS|HAPPENS TO IT",
  "{P}|IS KEEPING|AN EYE OUT",
  "{P}|IS STILL|UPSET ABOUT|EARLIER",
  "{P}|THINKS BAD|LUCK FOLLOWS|IT AROUND",
  "{P}|IS CHECKING|ITS POCKETS",
  "{P}|IS LOOKING|OVER ITS|SHOULDER",
  "{P}|THINKS|TODAY IS|CURSED",
  "{P}|WANTS THIS|DAY TO END",
  "{P}|IS STILL|GRUMBLING",
};

// CHEERFUL nature
const char* const TH_CHEERFUL[] = {
  "{P}|THINKS LIFE|IS BEAUTIFUL",
  "{P}|IS GLAD|YOU'RE HERE",
  "{P}|THINKS|EVERY DAY IS|A GIFT",
  "{P}|IS SMILING|AT NOTHING|IN PARTICULAR",
  "{P}|FEELS|REALLY GOOD",
  "{P}|THINKS IT'S|A WONDERFUL|WORLD",
  "{P}|HAS|SUNSHINE IN|ITS POCKETS",
  "{P}|LOVES|EVERYTHING|TODAY",
  "{P}|IS WAVING|AT YOU",
  "{P}|IS SPREADING|GOOD VIBES",
  "{P}|THINKS YOU|LOOK NICE|TODAY",
  "{P}|IS HUMMING|HAPPILY",
  "{P}|IS GRATEFUL|FOR TODAY",
  "{P}|THINKS|THINGS WILL|WORK OUT",
  "{P}|IS LOOKING|ON THE|BRIGHT SIDE",
  "{P}|IS JUST|HAPPY",
};

// PLAYFUL nature
const char* const TH_PLAYFUL[] = {
  "{P}|WANTS TO|PLAY",
  "{P}|IS PLANNING|THE PERFECT|HIDING SPOT",
  "{P}|TAGGED YOU.|YOU'RE IT",
  "{P}|WANTS TO DO|SOMETHING FUN",
  "{P}|IS BORED.|VERY BORED",
  "{P}|IS ZOOMING|AROUND",
  "{P}|WANTS TO|RACE YOU",
  "{P}|HAS TOO|MUCH ENERGY",
  "{P}|IS HIDING.|POORLY",
  "{P}|IS DARING|YOU TO|CATCH IT",
  "{P}|WANTS TO|PLAY A GAME",
  "{P}|IS BOUNCING|OFF THE|WALLS",
  "{P}|IS MAKING|SILLY FACES",
  "{P}|THINKS|EVERYTHING|IS A GAME",
  "{P}|IS DOING|A SPIN",
  "{P}|IS LOOKING|FOR MISCHIEF",
};

// GLUTTON nature
const char* const TH_GLUTTON[] = {
  "{P}|IS ASKING|ABOUT DESSERT",
  "{P}|ISN'T|HUNGRY. BUT|IT COULD EAT",
  "{P}|THINKS IT'S|SNACK O'CLOCK",
  "{P}|WANTS|SECOND|BREAKFAST",
  "{P}|IS DREAMING|OF SWEET|FRUIT",
  "{P}|THINKS ONE|MORE BITE|WON'T HURT",
  "{P}|THINKS CAKE|IS A FOOD|GROUP",
  "{P}|SMELLS|FOOD. OR|WANTS FOOD",
  "{P}|IS THINKING|ABOUT LUNCH.|AND DINNER",
  "{P}|WANTS TO|EAT AGAIN",
  "{P}|IS PLANNING|ITS NEXT|SNACK",
  "{P}|THINKS THE|FARM NEEDS|MORE POTS",
  "{P}|IS LICKING|ITS LIPS",
  "{P}|THINKS IT|SMELLS CAKE",
  "{P}|IS STILL|THINKING|ABOUT FOOD",
  "{P}|HAS ROOM|FOR MORE",
};

// LAZY nature
const char* const TH_LAZY[] = {
  "{P}|THINKS|WALKING IS|TOO MUCH WORK",
  "{P}|WANTS|A NAP.|RIGHT NOW",
  "{P}|WILL DO IT|TOMORROW",
  "{P}|IS|LOUNGING",
  "{P}|THINKS|MOVING IS|OVERRATED",
  "{P}|SAYS SLEEP|IS ITS|HOBBY",
  "{P}|DOESN'T|WANT TO BE|BOTHERED",
  "{P}|IS TOO|COMFY TO|CARE",
  "{P}|IS DOING|THE BARE|MINIMUM",
  "{P}|IS RESTING|ITS EYES",
  "{P}|THINKS NAPS|ARE A|LIFESTYLE",
  "{P}|IS NOT|GETTING UP",
  "{P}|WANTS YOU|TO DO IT",
  "{P}|IS|RECHARGING",
  "{P}|THINKS|TODAY IS A|REST DAY",
  "{P}|IS STARING|AT THE|CEILING",
};

// BRAVE nature
const char* const TH_BRAVE[] = {
  "{P}|WANTS THE|NEXT FIGHT",
  "{P}|FEARS|NOTHING.|EXCEPT BATHS",
  "{P}|THINKS|BOSSES SHOULD|FEAR IT",
  "{P}|WAS BORN|FOR THIS",
  "{P}|IS SCANNING|THE HORIZON",
  "{P}|SAYS DANGER|IS ITS|MIDDLE NAME",
  "{P}|WANTS TO|GO DEEPER",
  "{P}|IS|SHADOWBOXING",
  "{P}|IS FLEXING",
  "{P}|IS READY|TO RUMBLE",
  "{P}|THINKS IT|CAN TAKE|ANYONE",
  "{P}|WANTS A|REAL|CHALLENGE",
  "{P}|IS STANDING|TALL",
  "{P}|THINKS|BOSSES ARE|JUST BIG FOES",
  "{P}|IS BORED|WITHOUT A|FIGHT",
  "{P}|IS ITCHING|FOR BATTLE",
};

// GREEDY nature
const char* const TH_GREEDY[] = {
  "{P}|WANTS MORE|CREDITS.|ALWAYS MORE",
  "{P}|THOUGHT IT|SAW A CREDIT|ON THE FLOOR",
  "{P}|IS DROWNING|IN RICHES",
  "{P}|IS COUNTING|ITS CREDITS|AGAIN",
  "{P}|LOVES A|GOOD DEAL",
  "{P}|WANTS YOU|TO SAVE YOUR|CREDITS",
  "{P}|THINKS IT|SHOULD BE|RICHER",
  "{P}|HEARS THE|SLOTS CALLING",
  "{P}|IS GUARDING|ITS CREDITS",
  "{P}|IS HAGGLING|WITH ITSELF",
  "{P}|WANTS TO|INVEST",
  "{P}|IS CHECKING|THE PRICES",
  "{P}|THINKS IT|DESERVES|A RAISE",
  "{P}|IS POLISHING|A CREDIT",
  "{P}|WANTS A|BIGGER WALLET",
  "{P}|IS DREAMING|OF RICHES",
};

// TIMID nature
const char* const TH_TIMID[] = {
  "{P}|HEARD A|NOISE",
  "{P}|IS STAYING|OVER HERE",
  "{P}|WONDERS IF|IT'S SAFE|TO COME OUT",
  "{P}|HOPES FOR|NO SURPRISES|TODAY",
  "{P}|DOESN'T|LIKE THE|DARK",
  "{P}|IS STAYING|CLOSE TO YOU",
  "{P}|ISN'T|SCARED. JUST|CAREFUL",
  "{P}|IS PEEKING|AROUND",
  "{P}|IS HIDING|BEHIND YOU",
  "{P}|JUMPED AT|ITS OWN|SHADOW",
  "{P}|IS TIPTOEING",
  "{P}|IS BEING|VERY QUIET",
  "{P}|HOPES|NOBODY SAW|THAT",
  "{P}|IS LOOKING|FOR A SAFE|SPOT",
  "{P}|IS|TREMBLING|A LITTLE",
  "{P}|FEELS SAFE|WITH YOU",
};

// GRUMPY nature
const char* const TH_GRUMPY[] = {
  "{P}|WANTS TO|KNOW WHAT|YOU WANT",
  "{P}|IS NOT IN|THE MOOD",
  "{P}|SUPPOSES|THIS IS FINE",
  "{P}|THINKS|PETS ARE|OVERRATED",
  "{P}|WANTS TO BE|LEFT ALONE.|BUT NOT FAR",
  "{P}|FINDS|EVERYTHING|ANNOYING",
  "{P}|HAS BEEN|THROUGH WORSE",
  "{P}|ROLLED|ITS EYES",
  "{P}|IS|MUTTERING",
  "{P}|THINKS|TODAY IS|OVERRATED",
  "{P}|IS GLARING|AT NOTHING",
  "{P}|WANTS|PEACE AND|QUIET",
  "{P}|IS NOT|IMPRESSED",
  "{P}|SIGHED|LOUDLY",
  "{P}|IS JUDGING|YOU",
  "{P}|GRUNTED",
};

#pragma endregion

#pragma region DREAMS

// Any night, no condition
const char* const DR_GENERAL[] = {
  "{P}|DREAMT IT|COULD FLY",
  "{P}|DREAMT OF A|GIANT CAKE|WITH LEGS",
  "{P}|DREAMT IT|WAS A TINY|DRAGON",
  "{P}|DREAMT THE|MOON WAS|A COOKIE",
  "{P}|DREAMT OF|SWIMMING IN|SWEET FRUIT",
  "{P}|DREAMT IT|FOUND A|SECRET DOOR",
  "{P}|DREAMT THE|FLOOR WAS|MADE OF JELLY",
  "{P}|DREAMT OF|A WORLD WITH|NO BEDTIME",
  "{P}|DREAMT IT|WAS THE|SHOPKEEPER",
  "{P}|DREAMT IT|HAD TWELVE|LEGS",
  "{P}|DREAMT OF|RAINING|GEMS",
  "{P}|DREAMT IT|TALKED TO|A CLOUD",
  "{P}|DREAMT ITS|SHADOW RAN|AWAY",
  "{P}|DREAMT OF|A CASTLE|MADE OF CARDS",
  "{P}|DREAMT IT|WAS A FISH.|BLUB BLUB",
  "{P}|DREAMT ABOUT|{E}|AGAIN",
  "{P}|DREAMT|{E}|STOLE ITS HAT",
  "{P}|DREAMT|{E}|BECAME MAYOR",
  "{P}|DREAMT IT|WON A|DANCE CONTEST",
  "{P}|DREAMT OF|A STAR THAT|KNEW ITS NAME",
  "{P}|DREAMT IT|ATE THE|WHOLE SHOP",
  "{P}|DREAMT OF|AN ENDLESS|STAIRCASE",
  "{P}|DREAMT IT|GREW AS TALL|AS A TREE",
  "{P}|DREAMT OF|A TALKING|POTION",
  "{P}|DREAMT THE|SCREEN WAS|UPSIDE DOWN",
  "{P}|DREAMT OF|SOMETHING.|IT FORGOT",
  "{P}|DREAMT IT|HAD A|PET BEAR",
  "{P}|DREAMT OF|A FOREST OF|LOLLIPOPS",
  "{P}|DREAMT IT|COULD READ|MINDS",
  "{P}|DREAMT OF A|BATTLE WITH|A TEACUP",
  "{P}|DREAMT IT|RODE A|GIANT BALLOON",
  "{P}|DREAMT THE|STARS WERE|SINGING",
  "{P}|DREAMT IT|WAS FAMOUS",
  "{P}|DREAMT OF|A DOOR THAT|LED TO NAPS",
  "{P}|DREAMT IT|WAS A KNIGHT|IN SHINY GEAR",
  "{P}|DREAMT OF|A RIVER OF|ENERGY DRINK",
  "{P}|DREAMT IT|LOST ITS|FEET",
  "{P}|DREAMT IT|WAS A CARD|IN A DECK",
  "{P}|DREAMT OF|A HUGE|WARM BLANKET",
  "{P}|DREAMT IT|INVENTED|A NEW COLOR",
  "{P}|DREAMT IT|WAS A CLOUD",
  "{P}|DREAMT OF|A TOWN OF|TINY PICOS",
  "{P}|DREAMT IT|COULD BREATHE|UNDERWATER",
  "{P}|DREAMT OF|A SKY FULL|OF CARDS",
  "{P}|DREAMT IT|WAS RUNNING|IN PLACE",
  "{P}|DREAMT THE|SHOP WAS|ALL FREE",
  "{P}|DREAMT OF A|DOOR WITH NO|HANDLE",
  "{P}|DREAMT IT|FELL UP|INSTEAD",
  "{P}|DREAMT OF|A TRAIN MADE|OF CAKE",
  "{P}|DREAMT IT|WAS A GHOST.|BOO",
  "{P}|DREAMT IT|FORGOT HOW|TO WALK",
  "{P}|DREAMT OF|A GIANT|DUCK",
  "{P}|DREAMT IT|COULD TALK|TO BIRDS",
  "{P}|DREAMT OF|A HOUSE ON|A TURTLE",
  "{P}|DREAMT IT|WAS A|SHOOTING STAR",
  "{P}|DREAMT OF|ITS BIRTHDAY|PARTY",
  "{P}|DREAMT IT|WAS IN A|SNOW GLOBE",
  "{P}|DREAMT OF|BUBBLES.|LOTS OF THEM",
  "{P}|DREAMT IT|WAS A|WIZARD",
  "{P}|DREAMT OF|A GIANT|SNAIL RACE",
  "{P}|DREAMT|{E}|WAS A CAT",
  "{P}|DREAMT|{E}|SANG OPERA",
  "{P}|DREAMT OF|{E}|AS A PAL",
  "{P}|DREAMT OF|A MAZE WITH|NO EXIT",
  "{P}|DREAMT IT|WAS ON TV",
  "{P}|DREAMT OF|A TREE THAT|GREW GEMS",
  "{P}|DREAMT IT|SWAPPED|BODIES",
  "{P}|DREAMT THE|BATTERY|RAN OUT",
  "{P}|DREAMT OF|A LIBRARY|OF NAPS",
  "{P}|DREAMT IT|WAS A PIRATE",
  "{P}|DREAMT OF|A WHALE IN|THE SKY",
  "{P}|DREAMT IT|LOST A TOOTH",
  "{P}|DREAMT OF|A FLOATING|ISLAND",
  "{P}|DREAMT IT|HAD WINGS",
  "{P}|DREAMT OF|A LONG TRIP|BY BOAT",
  "{P}|DREAMT IT|WAS A GIANT|IN TINY TOWN",
  "{P}|DREAMT OF|A CANDLE|THAT GLOWED",
  "{P}|DREAMT IT|WAS LATE FOR|SOMETHING",
  "{P}|DREAMT OF|A FROG KING",
  "{P}|DREAMT|NOTHING.|JUST DARK",
};

// Won a battle today
const char* const DR_WON[] = {
  "{P}|DREAMT OF|TODAY'S|BIG WIN",
  "{P}|DREAMT A|CROWD WAS|CHEERING",
  "{P}|DREAMT IT|WON A GOLD|TROPHY",
  "{P}|DREAMT IT|WAS|UNDEFEATED",
  "{P}|DREAMT IT|WON AGAIN|AND AGAIN",
  "{P}|DREAMT OF|A PARADE IN|ITS HONOR",
  "{P}|DREAMT IT|WAS A|CHAMPION",
  "{P}|DREAMT OF|A WALL OF|MEDALS",
};

// Lost a battle today
const char* const DR_LOST[] = {
  "{P}|DREAMT ABOUT|THE FIGHT IT|LOST",
  "{P}|DREAMT IT|GOT A REMATCH|AND WON",
  "{P}|HAD A|NIGHTMARE|ABOUT FIRE",
  "{P}|DREAMT THE|ENEMY WAS|LAUGHING",
  "{P}|DREAMT IT|KEPT MISSING|ITS ATTACKS",
  "{P}|DREAMT OF|A FIGHT IT|COULDN'T WIN",
  "{P}|DREAMT ITS|CARDS WERE|ALL BLANK",
  "{P}|DREAMT IT|TRAINED ALL|NIGHT",
};

// Beat a boss today
const char* const DR_BOSS[] = {
  "{P}|DREAMT THE|BOSS WAS|ITS FRIEND",
  "{P}|DREAMT IT|WAS THE|BOSS NOW",
  "{P}|DREAMT OF A|BOSS EVEN|BIGGER",
  "{P}|DREAMT IT|WORE THE|BOSS'S CROWN",
  "{P}|DREAMT OF|THE BOSS|FIGHT AGAIN",
  "{P}|DREAMT IT|GOT A BOSS|TROPHY",
  "{P}|DREAMT THE|BOSS WANTED|A REMATCH",
  "{P}|DREAMT IT|WAS TEN|FEET TALL",
};

// Hit a slots jackpot today
const char* const DR_JACKPOT[] = {
  "{P}|DREAMT OF|SPINNING|SLOTS",
  "{P}|DREAMT OF|A MOUNTAIN|OF CREDITS",
  "{P}|DREAMT IT|BROKE THE|SLOT MACHINE",
  "{P}|DREAMT IT|HIT TWO|JACKPOTS",
  "{P}|DREAMT OF|SEVENS.|ALL SEVENS",
  "{P}|DREAMT THE|SLOTS NEVER|STOPPED",
  "{P}|DREAMT OF|A GOLDEN|LEVER",
  "{P}|DREAMT IT|WAS THE|HOUSE",
};

// Got new gear today
const char* const DR_GEAR[] = {
  "{P}|DREAMT IT|WORE ALL ITS|GEAR AT ONCE",
  "{P}|DREAMT OF A|FASHION|SHOW",
  "{P}|DREAMT ITS|NEW GEAR|COULD TALK",
  "{P}|DREAMT OF|THE PERFECT|OUTFIT",
  "{P}|DREAMT ITS|GEAR WAS|GLOWING",
  "{P}|DREAMT OF|A CLOSET|WITH NO END",
  "{P}|DREAMT IT|WORE A|CROWN",
  "{P}|DREAMT OF|A MIRROR|THAT CHEERED",
};

// Harvested today
const char* const DR_HARVEST[] = {
  "{P}|DREAMT THE|FARM GREW|TO THE SKY",
  "{P}|DREAMT IT|WAS A GIANT|SWEET FRUIT",
  "{P}|DREAMT THE|POTS WERE|SINGING",
  "{P}|DREAMT OF|ENDLESS|HARVESTS",
  "{P}|DREAMT OF|A FIELD OF|SWEET FRUIT",
  "{P}|DREAMT THE|PLANTS COULD|WALK",
  "{P}|DREAMT IT|WAS A|SCARECROW",
  "{P}|DREAMT OF|A GOLDEN|POT",
};

// Good random event today
const char* const DR_GOOD_EVENT[] = {
  "{P}|DREAMT ABOUT|TODAY'S|LUCKY BREAK",
  "{P}|DREAMT OF|A FRIENDLY|STRANGER",
  "{P}|DREAMT OF|A SURPRISE|PARTY",
  "{P}|DREAMT LUCK|FOLLOWED IT|EVERYWHERE",
  "{P}|DREAMT OF|A FOUR LEAF|CLOVER",
  "{P}|DREAMT OF|A SHOOTING|STAR",
  "{P}|DREAMT OF|A GIFT WITH|ITS NAME",
  "{P}|DREAMT|EVERYTHING|WENT RIGHT",
};

// Bad random event today
const char* const DR_BAD_EVENT[] = {
  "{P}|DREAMT EVIL|DAVE CHASED|IT",
  "{P}|DREAMT A|THIEF TOOK|ITS SOCKS",
  "{P}|DREAMT OF|A DARK|STORM",
  "{P}|HAD A|BAD DREAM.|STILL SHAKY",
  "{P}|DREAMT OF|A MASKED|STRANGER",
  "{P}|DREAMT IT|WAS LOST|IN A STORM",
  "{P}|DREAMT ITS|POCKETS HAD|HOLES",
  "{P}|DREAMT OF|A CURSED|STATUE",
};

// Hunger 30 or less while asleep
const char* const DR_HUNGRY[] = {
  "{P}|DREAMT OF|FOOD.|ONLY FOOD",
  "{P}|DREAMT ITS|BED WAS A|GIANT SNACK",
  "{P}|HEARD ITS|TUMMY GROWL|IN ITS DREAM",
  "{P}|DREAMT OF|A FEAST IT|COULDN'T EAT",
  "{P}|DREAMT OF|A BOTTOMLESS|PLATE",
  "{P}|DREAMT IT|ATE ITS|PILLOW",
  "{P}|DREAMT OF|SWEET FRUIT|RAIN",
  "{P}|DREAMT THE|FRIDGE WAS|EMPTY",
};

// CHEERFUL nature
const char* const DR_CHEERFUL[] = {
  "{P}|DREAMT OF|A RAINBOW|JUST FOR IT",
  "{P}|DREAMT|EVERYONE|WAS SMILING",
  "{P}|DREAMT OF|SUNSHINE|AND HUGS",
  "{P}|HAD A HAPPY|DREAM. IT|FORGOT IT",
  "{P}|DREAMT YOU|BOTH WENT ON|A PICNIC",
  "{P}|DREAMT OF|A WARM|SUNNY DAY",
  "{P}|DREAMT OF|SINGING|WITH BIRDS",
  "{P}|DREAMT OF|A FIELD OF|FLOWERS",
  "{P}|DREAMT|EVERYONE|WAS FRIENDS",
  "{P}|DREAMT YOU|WERE THERE.|IT WAS NICE",
};

// PLAYFUL nature
const char* const DR_PLAYFUL[] = {
  "{P}|DREAMT OF|THE BIGGEST|GAME OF TAG",
  "{P}|DREAMT IT|HID SO WELL|NOBODY WON",
  "{P}|DREAMT OF|A PLAYGROUND|IN THE SKY",
  "{P}|DREAMT IT|BOUNCED ALL|NIGHT",
  "{P}|DREAMT OF|A NEVER|ENDING GAME",
  "{P}|DREAMT OF|A GIANT|BOUNCY HOUSE",
  "{P}|DREAMT IT|WON HIDE|AND SEEK",
  "{P}|DREAMT OF|A SLIDE TO|THE MOON",
  "{P}|DREAMT OF|A PILLOW|FIGHT",
  "{P}|DREAMT IT|PLAYED ALL|DAY LONG",
};

// GLUTTON nature
const char* const DR_GLUTTON[] = {
  "{P}|DREAMT OF|A MOUNTAIN|OF CAKE",
  "{P}|DREAMT IT|ATE THE|MOON",
  "{P}|DREAMT OF|AN ENDLESS|BUFFET",
  "{P}|DREAMT THE|FARM GREW|ONLY DESSERT",
  "{P}|DREAMT OF|SNACKS. IT'S|STILL HUNGRY",
  "{P}|DREAMT OF|A RIVER OF|SYRUP",
  "{P}|DREAMT IT|LIVED IN A|BAKERY",
  "{P}|DREAMT OF|A CAKE WITH|TEN LAYERS",
  "{P}|DREAMT IT|ATE A WHOLE|FARM",
  "{P}|DREAMT OF|SECONDS.|AND THIRDS",
};

// LAZY nature
const char* const DR_LAZY[] = {
  "{P}|DREAMT IT|WAS SLEEPING|IN A DREAM",
  "{P}|DREAMT OF|A BIGGER,|COMFIER BED",
  "{P}|DREAMT IT|NEVER HAD|TO WAKE UP",
  "{P}|DREAMT OF|A CLOUD|PILLOW",
  "{P}|DREAMT IT|TOOK A NAP|IN ITS DREAM",
  "{P}|DREAMT OF|A HAMMOCK",
  "{P}|DREAMT IT|WON A NAP|CONTEST",
  "{P}|DREAMT OF|DOING|NOTHING",
  "{P}|DREAMT OF|SLEEPING IN",
  "{P}|DREAMT THE|DAY HAD NO|MORNING",
};

// BRAVE nature
const char* const DR_BRAVE[] = {
  "{P}|DREAMT IT|BEAT A|DRAGON",
  "{P}|DREAMT OF|THE DEEPEST|DUNGEON FLOOR",
  "{P}|DREAMT OF|AN ENDLESS|LINE OF FOES",
  "{P}|DREAMT IT|WAS A HERO|IN A CAPE",
  "{P}|DREAMT IT|BEAT EVERY|BOSS AT ONCE",
  "{P}|DREAMT IT|LED AN ARMY",
  "{P}|DREAMT OF|A HUNDRED|BOSSES",
  "{P}|DREAMT IT|SAVED THE|DAY",
  "{P}|DREAMT IT|BEAT EVIL|DAVE FOR GOOD",
  "{P}|DREAMT OF|A LEGENDARY|SWORD",
};

// GREEDY nature
const char* const DR_GREEDY[] = {
  "{P}|DREAMT OF|SWIMMING IN|CREDITS",
  "{P}|DREAMT IT|OWNED THE|WHOLE SHOP",
  "{P}|DREAMT OF|A GEM AS|BIG AS IT",
  "{P}|DREAMT OF|A VAULT.|ALL ITS OWN",
  "{P}|DREAMT IT|NEVER SPENT|A CREDIT",
  "{P}|DREAMT OF|A CREDIT|FOUNTAIN",
  "{P}|DREAMT IT|WAS A KING",
  "{P}|DREAMT OF|A TREASURE|CHEST",
  "{P}|DREAMT IT|FOUND A|GOLD MINE",
  "{P}|DREAMT OF|ITS OWN|BANK",
};

// TIMID nature
const char* const DR_TIMID[] = {
  "{P}|DREAMT IT|HID UNDER|A BIG LEAF",
  "{P}|DREAMT|SOMETHING|WAS FOLLOWING",
  "{P}|DREAMT OF|A SAFE,|QUIET PLACE",
  "{P}|DREAMT IT|WAS BRAVE",
  "{P}|DREAMT THE|DARK WAS|FRIENDLY",
  "{P}|DREAMT OF|A COZY|BLANKET FORT",
  "{P}|DREAMT|SOMETHING|SAID BOO",
  "{P}|DREAMT IT|WAS|INVISIBLE",
  "{P}|DREAMT YOU|KEPT IT SAFE",
  "{P}|DREAMT OF|A NIGHT|LIGHT",
};

// GRUMPY nature
const char* const DR_GRUMPY[] = {
  "{P}|HAD AN|ANNOYING|DREAM",
  "{P}|DREAMT|EVERYONE|LEFT IT ALONE",
  "{P}|DREAMT OF|A SNACK.|IT WAS STALE",
  "{P}|DREAMT IT|WAS HAPPY.|WEIRD",
  "{P}|WON'T TALK|ABOUT ITS|DREAM",
  "{P}|DREAMT OF|A RAIN CLOUD|OVERHEAD",
  "{P}|DREAMT IT|WAS STUCK|IN A LINE",
  "{P}|DREAMT OF|A PEACEFUL|SILENCE",
  "{P}|DREAMT IT|SMILED.|ONCE",
  "{P}|DREAMT|EVERYONE|WAS LOUD",
};

#pragma endregion

#pragma region POOL TABLE
struct DialoguePool { const char* const* lines; uint16_t count; };
#define POOL(x) { x, sizeof(x) / sizeof(x[0]) }

enum DialoguePoolId {
  P_TH_GENERAL,
  P_TH_HUNGRY,
  P_TH_TIRED,
  P_TH_SAD,
  P_TH_ANGRY,
  P_TH_HAPPY,
  P_TH_LOW_HP,
  P_TH_INJURED,
  P_TH_COOLDOWN,
  P_TH_DEEP_DUNGEON,
  P_TH_CROPS_READY,
  P_TH_RICH,
  P_TH_BROKE,
  P_TH_WON,
  P_TH_LOST,
  P_TH_BOSS,
  P_TH_JACKPOT,
  P_TH_GEAR,
  P_TH_HARVEST,
  P_TH_GOOD_EVENT,
  P_TH_BAD_EVENT,
  P_TH_CHEERFUL,
  P_TH_PLAYFUL,
  P_TH_GLUTTON,
  P_TH_LAZY,
  P_TH_BRAVE,
  P_TH_GREEDY,
  P_TH_TIMID,
  P_TH_GRUMPY,
  P_DR_GENERAL,
  P_DR_WON,
  P_DR_LOST,
  P_DR_BOSS,
  P_DR_JACKPOT,
  P_DR_GEAR,
  P_DR_HARVEST,
  P_DR_GOOD_EVENT,
  P_DR_BAD_EVENT,
  P_DR_HUNGRY,
  P_DR_CHEERFUL,
  P_DR_PLAYFUL,
  P_DR_GLUTTON,
  P_DR_LAZY,
  P_DR_BRAVE,
  P_DR_GREEDY,
  P_DR_TIMID,
  P_DR_GRUMPY,
  P_COUNT
};

const DialoguePool dialoguePools[P_COUNT] = {
  POOL(TH_GENERAL),
  POOL(TH_HUNGRY),
  POOL(TH_TIRED),
  POOL(TH_SAD),
  POOL(TH_ANGRY),
  POOL(TH_HAPPY),
  POOL(TH_LOW_HP),
  POOL(TH_INJURED),
  POOL(TH_COOLDOWN),
  POOL(TH_DEEP_DUNGEON),
  POOL(TH_CROPS_READY),
  POOL(TH_RICH),
  POOL(TH_BROKE),
  POOL(TH_WON),
  POOL(TH_LOST),
  POOL(TH_BOSS),
  POOL(TH_JACKPOT),
  POOL(TH_GEAR),
  POOL(TH_HARVEST),
  POOL(TH_GOOD_EVENT),
  POOL(TH_BAD_EVENT),
  POOL(TH_CHEERFUL),
  POOL(TH_PLAYFUL),
  POOL(TH_GLUTTON),
  POOL(TH_LAZY),
  POOL(TH_BRAVE),
  POOL(TH_GREEDY),
  POOL(TH_TIMID),
  POOL(TH_GRUMPY),
  POOL(DR_GENERAL),
  POOL(DR_WON),
  POOL(DR_LOST),
  POOL(DR_BOSS),
  POOL(DR_JACKPOT),
  POOL(DR_GEAR),
  POOL(DR_HARVEST),
  POOL(DR_GOOD_EVENT),
  POOL(DR_BAD_EVENT),
  POOL(DR_HUNGRY),
  POOL(DR_CHEERFUL),
  POOL(DR_PLAYFUL),
  POOL(DR_GLUTTON),
  POOL(DR_LAZY),
  POOL(DR_BRAVE),
  POOL(DR_GREEDY),
  POOL(DR_TIMID),
  POOL(DR_GRUMPY),
};
#pragma endregion
